# Generated by Django 3.0.3 on 2020-07-09 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=25)),
                ('clave', models.TextField(max_length=25)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='proyectos.Categoria'),
        ),
    ]
