# Generated by Django 3.0.3 on 2020-03-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='slack_bot_token',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
