# Generated by Django 3.0.3 on 2020-07-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_auto_20200709_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
