# Generated by Django 3.0.3 on 2020-03-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyecto_slack_bot_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='slack_channel_id',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
