# Generated by Django 3.0.3 on 2020-03-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_equipo_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
