# Generated by Django 3.0.3 on 2020-05-12 23:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0005_auto_20200302_0159'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipo',
            unique_together={('proyecto', 'usuario')},
        ),
    ]
