# Generated by Django 3.0.3 on 2020-02-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_auto_20200228_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='prioridad',
            name='clave',
            field=models.TextField(default='ninguno', max_length=25),
        ),
        migrations.AddField(
            model_name='prioridad',
            name='orden',
            field=models.SmallIntegerField(default=1),
        ),
    ]
