# Generated by Django 3.0.3 on 2020-02-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_auto_20200228_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjunto',
            name='archivo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adjunto',
            name='ruta',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
