# Generated by Django 3.0.3 on 2020-02-29 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_auto_20200229_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjunto',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjuntos', to='kanban.Tarea'),
        ),
    ]
