# Generated by Django 3.0.3 on 2020-02-29 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_auto_20200229_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to='kanban.Tarea'),
        ),
    ]
