# Generated by Django 3.0.3 on 2020-03-02 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanban', '0008_auto_20200229_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kanban.Tarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participante_asignado', to=settings.AUTH_USER_MODEL)),
                ('usuario_asigna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tareas_asignaciones',
            },
        ),
    ]
