# Generated by Django 3.0.3 on 2020-03-25 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_auto_20200302_0159'),
        ('kanban', '0010_auto_20200324_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='estatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='proyectos.Estatus'),
        ),
    ]
