# Generated by Django 3.0.3 on 2020-07-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0011_tarea_estatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=25)),
                ('clave', models.TextField(default='kanban', max_length=25)),
            ],
            options={
                'db_table': 'tipos_tarea',
            },
        ),
    ]
