# Generated by Django 3.0.3 on 2020-07-04 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0012_tipotarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='tipo_tarea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='kanban.TipoTarea'),
        ),
    ]
