# Generated by Django 3.0.3 on 2020-07-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0013_tarea_tipo_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fijar_en_kanban',
            field=models.BooleanField(default=True),
        ),
    ]
