# Generated by Django 3.0.3 on 2020-07-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0014_tarea_fijar_en_kanban'),
    ]

    operations = [
        migrations.AddField(
            model_name='listakanban',
            name='fijar_en_kanban',
            field=models.BooleanField(default=True),
        ),
    ]
