# Generated by Django 3.0.3 on 2020-03-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
